GET http://localhost:3000/users

### for local testing purposes

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "John Doe",
    "password": "securepassword123"
}

###

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "name": "John Doe",
    "password": "securepassword123"
}

### Connects to MongoDB and performs user authentication operations
### 1. Register a New User
POST http://localhost:5001/api/auth/register
Content-Type: application/json

{
    "username": "DemoStudent",
    "email": "student@csulb.edu",
    "password": "securePassword123"
}

### 2. Login (Success)
POST http://localhost:5001/api/auth/login
Content-Type: application/json

{
    "email": "student@csulb.edu",
    "password": "securePassword123"
}

### 3. Login (Fail - Wrong Password)
POST http://localhost:5001/api/auth/login
Content-Type: application/json

{
    "email": "student@csulb.edu",
    "password": "WrongPassword"
}

### 4. Get All Users (Demo)
GET http://localhost:5000/api/auth/all